### ISSUE TITLE
Add comment line for initialization of the Slack object.

### ISSUE THREAD

**Issue by Helveg** [yongzhenlow/slack-api#1]
The README states:
```
$Slack = new Slack('xoxp-0123456789-0123456789-0123456789-1a1a11');
```

But I don't know what that value is, is that a token of some sort? Could you add a comment line specifying what value to fill in there?

**Comment by yongzhenlow** [comment]
@Helveg In earlier implementations that was how authorizations worked, you can read more here https://api.slack.com/custom-integrations/legacy-tokens. The readme could use some updates, thanks for sharing!
